import { SAMPLE_FIXTURES } from "./fixtures";

const ROOT = `D:/trigyn/trigyn project/AI-recruiter-screening-system-`;

export const TEST_CATALOG = {
  unit: [
    { id: "test_unknown_extension", label: "test_extraction.py::test_unknown_extension", sub: "extract_text rejects .exe files (returns '')", command: "pytest tests/unit/test_extraction.py::test_unknown_extension -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_valid_json", label: "test_json.py::test_valid_json", sub: "safe_json_extract pulls JSON from prose", command: "pytest tests/unit/test_json.py::test_valid_json -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_invalid_json", label: "test_json.py::test_invalid_json", sub: "safe_json_extract returns None on non-JSON", command: "pytest tests/unit/test_json.py::test_invalid_json -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_safe_ollama_json_success", label: "test_ollama.py::test_safe_ollama_json_success", sub: "Ollama JSON parse + schema validation (happy path)", command: "pytest tests/unit/test_ollama.py::test_safe_ollama_json_success -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_safe_ollama_json_invalid_schema", label: "test_ollama.py::test_safe_ollama_json_invalid_schema", sub: "Fallback returned on schema violation", command: "pytest tests/unit/test_ollama.py::test_safe_ollama_json_invalid_schema -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_get_model_options_includes_installed_and_recommended", label: "test_ollama.py::test_get_model_options_includes_installed_and_recommended", sub: "Ollama list: installed first, dedupe, keep qwen3 + DEFAULT_OLLAMA_MODEL", command: "pytest tests/unit/test_ollama.py::test_get_model_options_includes_installed_and_recommended -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_get_model_options_uses_recommended_when_ollama_unavailable", label: "test_ollama.py::test_get_model_options_uses_recommended_when_ollama_unavailable", sub: "Recommended list returned when Ollama is down", command: "pytest tests/unit/test_ollama.py::test_get_model_options_uses_recommended_when_ollama_unavailable -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_get_model_options_returns_gemini_models", label: "test_ollama.py::test_get_model_options_returns_gemini_models", sub: "Gemini branch returns GEMINI_MODEL_OPTIONS", command: "pytest tests/unit/test_ollama.py::test_get_model_options_returns_gemini_models -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_jd_response_schema_requires_display_fields", label: "test_ollama.py::test_jd_response_schema_requires_display_fields", sub: "Schema requires experience, primary_skills, secondary_skills, education", command: "pytest tests/unit/test_ollama.py::test_jd_response_schema_requires_display_fields -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_match_score_range", label: "test_scoring.py::test_match_score_range", sub: "calculate_match_score returns float in [0, 100]", command: "pytest tests/unit/test_scoring.py::test_match_score_range -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_get_or_create_resume_embedding_uses_cached_faiss_row", label: "test_scoring.py::test_get_or_create_resume_embedding_uses_cached_faiss_row", sub: "Warm FAISS path reconstructs cached vector without re-encoding", command: "pytest tests/unit/test_scoring.py::test_get_or_create_resume_embedding_uses_cached_faiss_row -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_valid_pdf", label: "test_validation.py::test_valid_pdf", sub: "PDF magic %PDF-1.4 accepted", command: "pytest tests/unit/test_validation.py::test_valid_pdf -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_invalid_extension", label: "test_validation.py::test_invalid_extension", sub: ".exe rejected", command: "pytest tests/unit/test_validation.py::test_invalid_extension -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_fake_pdf", label: "test_validation.py::test_fake_pdf", sub: "b'NOTPDF' rejected", command: "pytest tests/unit/test_validation.py::test_fake_pdf -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
    { id: "test_large_file", label: "test_validation.py::test_large_file", sub: "Files >10 MB rejected", command: "pytest tests/unit/test_validation.py::test_large_file -v --junit-xml=reports/junit.json", cwd: ROOT, kind: "pytest", file: ROOT + "/reports/junit.json" },
  ],
  performance: [
    { id: "k6_score_endpoint", label: "k6 load test (POST /analyze)", sub: "Threshold p95<8s, success>90%", detail: "Ramp 0->10 VUs (2m), hold 10 VUs (30m soak), ramp down (2m)", command: "k6 run score_endpoint.js --out json=../../../reports/k6-results.json", cwd: ROOT + "/tests/performance/load", kind: "k6", file: ROOT + "/reports/k6-results.json" },
    { id: "k6_stress_test", label: "k6 stress test (capacity finding)", sub: "Ramp 0->50->100 VUs over ~6 min, threshold http_req_failed<0.50", detail: "Intentionally loose threshold - used to find the breaking point.", command: "k6 run stress_test.js --out json=../../../reports/k6-results.json", cwd: ROOT + "/tests/performance/load", kind: "k6", file: ROOT + "/reports/k6-results.json" },
    { id: "k6_soak_test", label: "k6 soak test (30 min, memory leak)", sub: "5 VUs, 30 min, p95<20s, error rate<10%", command: "k6 run soak_test.js --out json=../../../reports/k6-results.json", cwd: ROOT + "/tests/performance/load", kind: "k6", file: ROOT + "/reports/k6-results.json" },
    { id: "k6_upload_flow", label: "k6 upload flow (recruiter simulation)", sub: "Ramp 0->10->20 VUs, custom metrics upload_latency_ms / error_rate / total_uploads", command: "k6 run upload_flow.js --out json=../../../reports/k6-results.json", cwd: ROOT + "/tests/performance/load", kind: "k6", file: ROOT + "/reports/k6-results.json" },
    { id: "cprofile_run", label: "cProfile (extract_text + analyze_candidate_grading)", sub: "Top-30 frames by cumulative time", command: "python tests/performance/profiles/run_profiler.py", cwd: ROOT, kind: "python", file: ROOT + "/tests/performance/profiles/profile_results.txt" },
    { id: "lighthouse_run", label: "Lighthouse audit (frontend port 5173)", sub: "Performance, accessibility, SEO — outputs reports/lighthouse-report.html", detail: "Frontend must be running on port 5173 before running this.", command: 'npx --yes lighthouse http://localhost:5173 --output html --output-path "reports/lighthouse-report.html" --chrome-flags="--headless --no-sandbox"', cwd: ROOT, kind: "k6", file: ROOT + "/reports/lighthouse-report.html" },
    { id: "bm_test_cold_embedding", label: "test_cache_hit_speed.py::test_cold_embedding", sub: "Mean 4.47 ms, StdDev 0.42 ms (223 ops/s)", command: "pytest tests/performance/benchmarks/test_cache_hit_speed.py::test_cold_embedding --benchmark-only", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_warm_embedding", label: "test_cache_hit_speed.py::test_warm_embedding", sub: "Mean 1.20 ms, StdDev 0.30 ms", command: "pytest tests/performance/benchmarks/test_cache_hit_speed.py::test_warm_embedding --benchmark-only", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_docx_parse_speed", label: "test_parse_speed.py::test_docx_parse_speed", sub: "DOCX text extraction (in-memory)", command: "pytest tests/performance/benchmarks/test_parse_speed.py::test_docx_parse_speed --benchmark-only", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_pdf_parse_speed_data_engineer", label: "test_parse_speed.py::test_pdf_parse_speed[resume_data_engineer]", sub: "Mean 3.46 ms, StdDev 0.64 ms", command: "pytest tests/performance/benchmarks/test_parse_speed.py::test_pdf_parse_speed --benchmark-only -k resume_data_engineer", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_pdf_parse_speed_frontend", label: "test_parse_speed.py::test_pdf_parse_speed[resume_frontend]", sub: "Mean 3.46 ms, StdDev 0.64 ms", command: "pytest tests/performance/benchmarks/test_parse_speed.py::test_pdf_parse_speed --benchmark-only -k resume_frontend", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_pdf_parse_speed_junior", label: "test_parse_speed.py::test_pdf_parse_speed[resume_junior]", sub: "Mean 2.92 ms, StdDev 0.55 ms", command: "pytest tests/performance/benchmarks/test_parse_speed.py::test_pdf_parse_speed --benchmark-only -k resume_junior", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_pdf_parse_speed_strong_python", label: "test_parse_speed.py::test_pdf_parse_speed[resume_strong_python]", sub: "Mean 3.75 ms, StdDev 0.74 ms", command: "pytest tests/performance/benchmarks/test_parse_speed.py::test_pdf_parse_speed --benchmark-only -k resume_strong_python", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_embedding_speed", label: "test_embedding_speed.py::test_embedding_speed", sub: "Cold embedding benchmark (separate from cache test)", command: "pytest tests/performance/benchmarks/test_embedding_speed.py::test_embedding_speed --benchmark-only", cwd: ROOT, kind: "pytest" },
    { id: "bm_test_analyze_candidate_detail", label: "test_llm_only.py::test_analyze_candidate_detail [slow]", sub: "Real LLM call, skipped if Ollama is down", command: "pytest tests/performance/benchmarks/test_llm_only.py::test_analyze_candidate_detail --benchmark-only -m slow", cwd: ROOT, kind: "pytest" },
  ],
  integration: [
    { id: "scenario_matrix_all", label: "Scenario matrix (Playwright via run.ps1)", sub: "Runs all scenarios in tests/data/scenarios.yaml", command: "pwsh tests/run.ps1", cwd: ROOT, kind: "powershell", file: ROOT + "/reports/report.html" },
    { id: "scenario_python_ml_llama32", label: "Scenario: python_ml_llama32", sub: "model llama3.2 | expects resume_strong_python.pdf >= 50", command: "pwsh tests/run.ps1 -Filter python_ml_llama32", cwd: ROOT, kind: "powershell", file: ROOT + "/reports/report.html" },
    { id: "scenario_data_engineer_llama32", label: "Scenario: data_engineer_llama32", sub: "model llama3.2 | expects resume_data_engineer.pdf >= 45", command: "pwsh tests/run.ps1 -Filter data_engineer_llama32", cwd: ROOT, kind: "powershell", file: ROOT + "/reports/report.html" },
    { id: "scenario_frontend_react_llama32", label: "Scenario: frontend_react_llama32", sub: "model llama3.2 | expects resume_frontend.pdf >= 45", command: "pwsh tests/run.ps1 -Filter frontend_react_llama32", cwd: ROOT, kind: "powershell", file: ROOT + "/reports/report.html" },
    { id: "scenario_matrix_dry_run", label: "Scenario matrix (dry run, no pytest)", sub: "Prints the matrix and commands without invoking Ollama/uvicorn/pytest", command: "python tests/integration/run_scenario_matrix.py --dry-run", cwd: ROOT, kind: "python" },
  ],
};
